name: Cypress Tests

on: 
  workflow_dispatch:
    inputs: 
      cli:
        description: Run by cypress command line
        default: npx cypress run

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: npm install
    
      - name: Run E2E tests
        env:
          CYPRESS_FRONT_URL: ${{ secrets.FRONT_URL }}
          CYPRESS_SERVER: ${{ secrets.SERVER }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_EMAIL: ${{ secrets.EMAIL }}
          CYPRESS_LOGIN: ${{ secrets.LOGIN }}
          CYPRESS_USERS: ${{ secrets.USERS }}
        run: ${{ github.event.inputs.cli }}

      - name: Uploading files in case of failure
        uses: actions/upload-artifact@v4

        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore 

      - name: Upload files if successful
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore